### ISSUE TITLE
STAR shared memory does not work in the cluster environment

### ISSUE THREAD

**Issue by tAndreani** [BosingerLab/BALDR#11]
Hello,  
i am trying to run BALDR in the HPC environment but I have an issue related to the shared memory. (https://github.com/alexdobin/STAR/issues/841). I am wondering if there is a way to disabilitate that in BALDR. Given that you provide only one command (https://github.com/BosingerLab/BALDR), I do not see where there is the option to disabilitate the "shared memory" of STAR (that is also suggested in some cases).    

this is my command:  

```
./BALDR --paired no92_RL0659_D2_1.fastq.gz,no92_RL0659_D2_2.fastq.gz --trinity /path/Trinity --adapter /path/NexteraPE-PE.fa --trimmomatic  /path/trimmomatic-0.32.jar --igblastn /path/igblastn --STAR /site/ne/app/x86_64/star/v2.5.2b/STAR 
--STAR_index /path/BALDR-master/STAR_GRCh38/STAR_GRCh38_index  --BALDR /path/BALDR --memory 40 --threads 2
````

and this is the error:  

```
Shared memory error: 4, errno: Invalid argument(22)
EXITING because of FATAL ERROR: problems with shared memory: error from shmget() or shm_open().
SOLUTION: check shared memory settings as explained in STAR manual, OR run STAR with --genomeLoad NoSharedMemory to avoid using shared memory

```

Thank you in advance for any reply.
Best

**Comment by amit-upadhyay** [comment]
Hello,

I have changed the default to NoSharedMemory for STAR command. The LoadAndKeep option will be used when the --sharedMemory flag is specified. You can pull the changes and try again.

Thanks for the feedback.
Best.

**Comment by tAndreani** [comment]
Thank you, now it works. I have another issue: 

```
Error, do not understand options: --no_normalize_reads --output IG-mapped_Unmapped/Trinity/no92_RL0659_D2_1.IG-mapped_Unmapped_trinity
```
I am using this version of Trinity `Trinity v2.0.6`. Do you know if a older version of the one reccomended is preventing Trinity to work? You mention that new versions in respect of the one reccomended do not work. Before open new thickets I want to be sure about this.

Thank you very much for your help.

**Comment by amit-upadhyay** [comment]
I will look into the fastool dependency. My guess is that a newer version of one of the tools in the pipeline may have the fastool requirment. Thank you for pointing this out.
