### ISSUE TITLE
Possible bug (for --organism rhesus)?

### ISSUE THREAD

**Issue by julianqz** [BosingerLab/BALDR#2]
Lines 330-334. I was reading through the code and noticed this. 

Should `$read1_file_trimmed` on Lines 333 and 334 be `$read2_file_trimmed` instead?

`print "seqtk subseq $read1_file_trimmed FilterNonIG/Filtered_reads/$sample\.remnonIG.listreads | gzip  > FilterNonIG/Filtered_fastq/$sample\_1P.FilterNonIG.fastq.gz\n";
system "seqtk subseq $read1_file_trimmed FilterNonIG/Filtered_reads/$sample\.remnonIG.listreads | gzip  > FilterNonIG/Filtered_fastq/$sample\_1P.FilterNonIG.fastq.gz";

print "seqtk subseq $read1_file_trimmed FilterNonIG/Filtered_reads/$sample\.remnonIG.listreads | gzip  > FilterNonIG/Filtered_fastq/$sample\_2P.FilterNonIG.fastq.gz\n";
system "seqtk subseq $read1_file_trimmed FilterNonIG/Filtered_reads/$sample\.remnonIG.listreads | gzip  > FilterNonIG/Filtered_fastq/$sample\_2P.FilterNonIG.fastq.gz";
`

**Comment by amit-upadhyay** [comment]
Fixed. Thanks!
